export const UPS_CODE_SERVICES = {
  US: {
    '11': 'UPS Standard',
    '07': 'UPS Worldwide Express',
    '08': 'UPS Worldwide Expedited',
    '54': 'UPS Worldwide Express Plus',
    '65': 'UPS Worldwide Saver',
    '02': 'UPS 2nd Day Air',
    '59': 'UPS 2nd Day Air A.M.',
    '12': 'UPS 3 Day Select',
    '03': 'UPS Ground',
    '01': 'UPS Next Day Air',
    '14': 'UPS Next Day Air Early',
    '13': 'UPS Next Day Air Saver',
  },
  CA: {
    '11': 'UPS Standard',
    '12': 'UPS 3 Day Select',
    '13': 'UPS Express Saver',
    '14': 'UPS Express Early',
    '54': 'UPS Express Early',
    '65': 'UPS Express Saver',
    '70': 'UPS Access Point Economy',
    '02': 'UPS Expedited',
    '01': 'UPS Express',
    '08': 'UPS Worldwide Expedited',
    '07': 'UPS Worldwide Express',
  },

  MX: {
    '11': 'UPS Standard',
    '54': 'UPS Worldwide Express Plus',
    '65': 'UPS Worldwide Saver',
    '70': 'UPS Access Point Economy',
    '08': 'UPS Expedited',
    '07': 'UPS Express',
  },

  PL: {
    '11': 'UPS Standard',
    '54': 'UPS Express Plus',
    '65': 'UPS Express Saver',
    '70': 'UPS Access Point Economy',
    '82': 'UPS Today Standard',
    '83': 'UPS Today Dedicated Courier',
    '85': 'UPS Today Express',
    '86': 'UPS Today Express Saver',
    '08': 'UPS Expedited',
    '07': 'UPS Express',
  },

  PR: {
    '14': 'UPS Next Day Air Early',
    '54': 'UPS Worldwide Express Plus',
    '65': 'UPS Worldwide Saver',
    '02': 'UPS 2nd Day Air',
    '03': 'UPS Ground',
    '01': 'UPS Next Day Air',
    '08': 'UPS Worldwide Expedited',
    '07': 'UPS Worldwide Express',
  },

  EUROPEAN_UNION: {
    '11': 'UPS Standard',
    '54': 'UPS Worldwide Express Plus',
    '65': 'UPS Worldwide Saver',
    '70': 'UPS Access Point Economy',
    '08': 'UPS Expedited',
    '07': 'UPS Express',
    '74': 'UPS Express 12:00',
  },

  ALL_OTHER: {
    '11': 'UPS Standard',
    '17': 'UPS Worldwide Economy DDU',
    '54': 'UPS Worldwide Express Plus',
    '65': 'UPS Worldwide Saver',
    '71': 'UPS Worldwide Express Freight Midday',
    '72': 'UPS Worldwide Economy DDP',
    '96': 'UPS Worldwide Express Freight',
    '07': 'UPS Express',
    '08': 'UPS Worldwide Expedited',
  },
};
